apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-data-pvc
  namespace: rudn-yamadharma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi