apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: rudn-yamadharma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi